package prova.takeout;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

import lombok.Getter;
import lombok.Setter;
import sm.claudio.imaging.gpx.GeoCoord;
import sm.claudio.imaging.gpx.RicercaDicotomica;

public class ConvToTrk {
  private static final String            CSZ_HEAD   = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       //
      + "<gpx creator=\"Garmin Desktop App\" \n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
      + "     version=\"1.1\" \n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          //
      + "     xsi:schemaLocation=\"http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/WaypointExtension/v1 http://www8.garmin.com/xmlschemas/WaypointExtensionv1.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v1 http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www8.garmin.com/xmlschemas/GpxExtensionsv3.xsd http://www.garmin.com/xmlschemas/ActivityExtension/v1 http://www8.garmin.com/xmlschemas/ActivityExtensionv1.xsd http://www.garmin.com/xmlschemas/AdventuresExtensions/v1 http://www8.garmin.com/xmlschemas/AdventuresExtensionv1.xsd http://www.garmin.com/xmlschemas/PressureExtension/v1 http://www.garmin.com/xmlschemas/PressureExtensionv1.xsd http://www.garmin.com/xmlschemas/TripExtensions/v1 http://www.garmin.com/xmlschemas/TripExtensionsv1.xsd http://www.garmin.com/xmlschemas/TripMetaDataExtensions/v1 http://www.garmin.com/xmlschemas/TripMetaDataExtensionsv1.xsd http://www.garmin.com/xmlschemas/ViaPointTransportationModeExtensions/v1 http://www.garmin.com/xmlschemas/ViaPointTransportationModeExtensionsv1.xsd http://www.garmin.com/xmlschemas/CreationTimeExtension/v1 http://www.garmin.com/xmlschemas/CreationTimeExtensionsv1.xsd http://www.garmin.com/xmlschemas/AccelerationExtension/v1 http://www.garmin.com/xmlschemas/AccelerationExtensionv1.xsd http://www.garmin.com/xmlschemas/PowerExtension/v1 http://www.garmin.com/xmlschemas/PowerExtensionv1.xsd http://www.garmin.com/xmlschemas/VideoExtension/v1 http://www.garmin.com/xmlschemas/VideoExtensionv1.xsd\" \n"
      + "     xmlns=\"http://www.topografix.com/GPX/1/1\" \n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              //
      + "     xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" \n"
      + "     xmlns:wptx1=\"http://www.garmin.com/xmlschemas/WaypointExtension/v1\" \n"
      + "     xmlns:gpxtrx=\"http://www.garmin.com/xmlschemas/GpxExtensions/v3\" \n"
      + "     xmlns:gpxtpx=\"http://www.garmin.com/xmlschemas/TrackPointExtension/v1\" \n"
      + "     xmlns:gpxx=\"http://www.garmin.com/xmlschemas/GpxExtensions/v3\" \n"
      + "     xmlns:trp=\"http://www.garmin.com/xmlschemas/TripExtensions/v1\" \n"
      + "     xmlns:adv=\"http://www.garmin.com/xmlschemas/AdventuresExtensions/v1\" \n"
      + "     xmlns:prs=\"http://www.garmin.com/xmlschemas/PressureExtension/v1\" \n"
      + "     xmlns:tmd=\"http://www.garmin.com/xmlschemas/TripMetaDataExtensions/v1\" \n"
      + "     xmlns:vptm=\"http://www.garmin.com/xmlschemas/ViaPointTransportationModeExtensions/v1\" \n"
      + "     xmlns:ctx=\"http://www.garmin.com/xmlschemas/CreationTimeExtension/v1\" \n"
      + "     xmlns:gpxacc=\"http://www.garmin.com/xmlschemas/AccelerationExtension/v1\" \n"
      + "     xmlns:gpxpx=\"http://www.garmin.com/xmlschemas/PowerExtension/v1\" \n"
      + "     xmlns:vidx1=\"http://www.garmin.com/xmlschemas/VideoExtension/v1\">\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       //
      + "\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
      + "  <metadata>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
      + "    <link href=\"http://www.garmin.com\">\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      //
      + "      <text>Garmin International</text>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
      + "    </link>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
      + "    <time>%s</time>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
      + "    <bounds maxlat=\"%.10f\" maxlon=\"%.10f\" minlat=\"%.10f\" minlon=\"%.10f\" />\n" //
      + "  </metadata>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //
      + "\n";
  private static final String            CSZ_TRKHEA = "  <trk>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          //
      + "    <name>%s</name>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            //
      + "    <extensions>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               //
      + "      <gpxx:TrackExtension>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    //
      + "        <gpxx:DisplayColor>Yellow</gpxx:DisplayColor>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
      + "      </gpxx:TrackExtension>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   //
      + "    </extensions>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              //
      + "    <trkseg>\n";
  private static final String            CSZ_TRK    = "      <trkpt lat=\"%.10f\" lon=\"%.10f\">\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
      + "        <ele>%.0f</ele>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
      + "        <time>%s</time>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
      + "      </trkpt>\n";

  private static final String            CSZ_FOOTER = " </trkseg>\n" + "  </trk>\n"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
      + "</gpx>\n";
  private static final DateTimeFormatter s_fmtTimeZ = DateTimeFormatter.ofPattern("yyyy-MM-dd");
  @Getter @Setter
  private LocalDateTime                  minTime, maxTime;
  private double                         minLat, maxLat, minLon, maxLon;

  public ConvToTrk() {
    //
  }

  public void convToGPX(RicercaDicotomica<GeoCoord> p_li) {
    String sz = s_fmtTimeZ.format(minTime);
    String szDate = GeoCoord.s_fmtTimeZ.format(minTime);
    String szFileOut = String.format("Track_%s.gpx", sz);
    minLat = Double.MAX_VALUE;
    maxLat = Double.MIN_VALUE;
    minLon = Double.MAX_VALUE;
    maxLon = Double.MIN_VALUE;
    p_li.stream().forEach(s -> minmax(s));
    try (PrintWriter bos = new PrintWriter(new FileWriter(szFileOut))) {
      sz = String.format(Locale.US, CSZ_HEAD, szDate //
          , maxLat //
          , maxLon //
          , minLat //
          , minLon);
      bos.println(sz);
      sz = String.format(Locale.US, CSZ_TRKHEA, szFileOut);
      bos.println(sz);
      p_li.stream().forEach(s -> scriviTrk(bos, s));
      bos.println(CSZ_FOOTER);
      System.out.printf("Scritto GPX: %s\n", szFileOut);
    } catch (FileNotFoundException e) {
      e.printStackTrace();
    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  private Object minmax(GeoCoord p_s) {
    if ( !isInRange(p_s))
      return p_s;
    minLat = minLat > p_s.getLat() ? p_s.getLat() : minLat;
    maxLat = maxLat < p_s.getLat() ? p_s.getLat() : maxLat;
    minLon = minLon > p_s.getLon() ? p_s.getLon() : minLon;
    maxLon = maxLon < p_s.getLon() ? p_s.getLon() : maxLon;
    return p_s;
  }

  private boolean isInRange(GeoCoord p_s) {
    return minTime.isBefore(p_s.getDatetime()) && maxTime.isAfter(p_s.getDatetime());
  }

  private Object scriviTrk(PrintWriter pw, GeoCoord p_s) {
    if (p_s.getDatetime().isBefore(minTime) || p_s.getDatetime().isAfter(maxTime))
      return p_s;
    String szDt = GeoCoord.s_fmtTimeZ.format(p_s.getDatetime());
    String sz = String.format(Locale.US, CSZ_TRK //
        , p_s.getLat() //
        , p_s.getLon() //
        , p_s.getAlt() >= 0 ? p_s.getAlt() : 0f //
        , szDt);
    pw.print(sz);
    return p_s;
  }

}
